version: '3.1'
services:
  getfit-admin-app:
    container_name: getfit-admin-app
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - REACT_APP_USER_SERVICE_URL=http://103.63.25.22:8002/user-service/api
        - REACT_APP_ORDER_SERVICE_URL=http://103.63.25.22:8002/order-service/api
        - REACT_APP_APPOINTMENT_SERVICE_URL=http://103.63.25.22:8002/appointment-service
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

    
      
