export const initialParamsTable = {
  pageSize: 5,
  entries: ["5", "10", "15", "20", "25"],
  pageIndex: 0,
};

export const dataExample = {
  entities: [
    {
      id: 123,
      name: "Jhon Michael",
      email: "jhon@creative-tim.com",
      birth_date: "12 Januari 1997",
      status: 1,
      home_care: 10,
      tele_fisio: 5,
      in_clinic: 3,
      tools: 1,
      webinars: 10,
    },
    {
      id: 123,
      name: "Jhon Michael",
      email: "jhon@creative-tim.com",
      birth_date: "12 Januari 1997",
      status: 1,
      home_care: 10,
      tele_fisio: 5,
      in_clinic: 3,
      tools: 1,
      webinars: 10,
    },
    {
      id: 123,
      name: "Jhon Michael",
      email: "jhon@creative-tim.com",
      birth_date: "12 Januari 1997",
      status: 1,
      home_care: 10,
      tele_fisio: 5,
      in_clinic: 3,
      tools: 1,
      webinars: 10,
    },
    {
      id: 123,
      name: "Jhon Michael",
      email: "jhon@creative-tim.com",
      birth_date: "12 Januari 1997",
      status: 1,
      home_care: 10,
      tele_fisio: 5,
      in_clinic: 3,
      tools: 1,
      webinars: 10,
    },
    {
      id: 123,
      name: "Jhon Michael",
      email: "jhon@creative-tim.com",
      birth_date: "12 Januari 1997",
      status: 1,
      home_care: 10,
      tele_fisio: 5,
      in_clinic: 3,
      tools: 1,
      webinars: 10,
    },
  ],
};
